### ISSUE TITLE
Working with Tasks Plugin

### ISSUE THREAD

**Issue by Admorei** [vkostyanetsky/ObsidianTimesheet#2]
If this Plugin could somehow work with the Tasks Plugin and count the Time spent in Tasks that are scheduled for a given Day that would be the holy grail for me. Is something like that planned ?

**Comment by vkostyanetsky** [comment]
I haven't used Tasks before. Judging by its description, it works on a different principle: allowing you to work with tasks without having to add them directly to daily notes. At the moment, Timesheet doesn't support this, and I also have no plans to implement such functionality (since it didn't come to mind).

I'll look for some sort of Tasks API next week; probably there is a simple way to get the results of a query for tasks, which allows me to implement the Tasks plugin support in Timesheet relatively quickly. I'll keep you posted.

**Comment by vkostyanetsky** [comment]
Took a look. Currently, Obsidian Tasks doesn't provide an [API](https://publish.obsidian.md/tasks/Advanced/Tasks+Api) that enables you to get tasks according to a given query for further parsing in another plugin. Consequently, I see no quick solution for the task you are describing. It is possible, for sure, but I have no time frame to work on it in the near future.

**Comment by Admorei** [comment]
yeah I figured, that that will be a problem.  But thank you a lot for at least looking into it!
